/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/cppFiles/main.cc to edit this template
 */

/* 
 * File:   main.cpp
 * Author: Postl
 *
 * Created on January 4, 2022, 5:34 PM
 */

/*
 * Homework Assignment 1
 * Chapter 2 - Gaddis
 * Lauren Postlethwaite
 * 
 * Programming Problem #2
 * 2. Sales Prediction*/


#include <cstdlib>
#include <iostream>

using namespace std;

/*
 * The East Coast sales division of a company generates 58 percent
 * of total sales. Based on that percentage, write a program that will
 * predict how much the East Coast division will generate if the
 * company has $8.6 million in sales this year.
 */
int main(int argc, char** argv) {

    float perSls = .58; // Percent of total sales generated by EC division
    float sales = 8.6; // Total sales this year in millions of dollars
    float eProfit; // Total sales this year by EC division in millions of dollars
    
    eProfit = sales * perSls;
    
    cout << " The East Coast sales division generated $" << eProfit << " million in sales this year." << endl;
    
    return 0;
}

